name: Patrick Galvin
url: http://glvn-blog.github.io
description: My little home on the internet.

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
